### ISSUE TITLE
Invoking an action after having attached the debugger fails

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk-debugger#23]
```
(wskdb) attach hello
Attaching to hello
   Creating action trampoline
ok
(wskdb) invoke hello
Debug session requested
TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:51:11)
    at Object.fs.writeFile (fs.js:1193:13)
    at onTempDirCreation (/Users/andreas/Downloads/openwhisk-debugger-master/client/lib/debug-nodejs.js:78:9)
    at _dirCreated (/Users/andreas/Downloads/openwhisk-debugger-master/client/node_modules/tmp/lib/tmp.js:310:7)
    at FSReqWrap.oncomplete (fs.js:112:15)
TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:51:11)
    at Object.fs.writeFile (fs.js:1193:13)
    at onTempDirCreation (/Users/andreas/Downloads/openwhisk-debugger-master/client/lib/debug-nodejs.js:78:9)
    at _dirCreated (/Users/andreas/Downloads/openwhisk-debugger-master/client/node_modules/tmp/lib/tmp.js:310:7)
    at FSReqWrap.oncomplete (fs.js:112:15)

```

**Comment by jzaccone** [comment]
I"m having the same issue
